[project]
name = "flock-showcase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flock-core[all-tools]>=0.4.5",
    "ipykernel>=6.29.5",
    "mem0ai>=0.1.97",
]
